### PR TITLE
Remove dependency on 'crypto', which is unused and causes conflicts w…

### PR DESCRIPTION
**Pull request by strbean**
…ith pycryptodome on Mac and Windows environments

### CODE REVIEW

**Comment by strbean** [comment]
Addressed https://github.com/CyberSource/cybersource-rest-client-python/issues/48

**Review by gsamaroo — APPROVED** [review]

**Comment by steve-gr4vy** [comment]
This fixes an issue that I'm seeing when trying to add the SDK using poetry:

```
poetry add cybersource-rest-client-python
Using version ^0.0.29 for cybersource-rest-client-python

Updating dependencies
Resolving dependencies... (7.9s)

  AssertionError

  at ~/.poetry/lib/poetry/mixology/incompatibility.py:60 in __init__
       56│                     # intersection, they're mutually exclusive, making this incompatibility
       57│                     # irrelevant, since we already know that mutually exclusive version
       58│                     # ranges are incompatible. We should never derive an irrelevant
       59│                     # incompatibility.
    →  60│                     assert by_ref[ref] is not None
       61│                 else:
       62│                     by_ref[ref] = term
       63│ 
       64│             new_terms = []
```

For now I've worked around by installing this branch instead `poetry add git+https://github.com/strbean/cybersource-rest-client-python#remove-crypto`

**Comment by steve-gr4vy** [comment]
@ snavinch could you take a look at this please?

**Comment by tbrlpld** [comment]
This is still causing issues. Any reason this is not merged although it's approved @gnongsie ?

**Comment by gnongsie** [comment]
We are looking at this in #84. Kindly give us some time to get it tested and released.

**Pull request closed without merging**
